package batalla.vista;

/**
 * Formulario para mostrar los detalles de una partida cargada.
 */
public class formHistorial extends javax.swing.JFrame {

    /**
     * Creates new form formHistorial
     */
    public formHistorial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCombatLog = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblEs1 = new javax.swing.JLabel();
        lblEs2 = new javax.swing.JLabel();
        lblEs3 = new javax.swing.JLabel();
        lblEs4 = new javax.swing.JLabel();
        lvlEs5 = new javax.swing.JLabel();
        lblEs6 = new javax.swing.JLabel();
        lblEs7 = new javax.swing.JLabel();
        lblEs5 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCombatLog.setEditable(false);
        txtCombatLog.setColumns(20);
        txtCombatLog.setRows(5);
        txtCombatLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Combat Log"));
        jScrollPane1.setViewportView(txtCombatLog);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas"));

        lblEs1.setText("Mayor daño en un solo ataque:");

        lblEs2.setText("Batalla mas larga:");

        lblEs3.setText("Total de armas invocadas heroe:");

        lblEs4.setText("Ataques supremos ejecutados heroe:");

        lvlEs5.setText("Ataques supremos ejecutados villano:");

        lblEs6.setText("Winrate heroe %:");

        lblEs7.setText("Winrate villano %:");

        lblEs5.setText("Total de armas invocadas villano:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEs1)
                    .addComponent(lblEs2)
                    .addComponent(lblEs3)
                    .addComponent(lblEs4)
                    .addComponent(lvlEs5)
                    .addComponent(lblEs6)
                    .addComponent(lblEs7)
                    .addComponent(lblEs5))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEs1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lvlEs5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEs7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Historial de Batalla");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel4)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Métodos para el ControladorFormHistorial (adaptados a los componentes
    // actuales)

    public void setCombatLog(String log) {
        txtCombatLog.setText(log);
    }

    public void setMayorDanio(String texto) {
        lblEs1.setText("Mayor daño en un solo ataque: " + texto);
    }

    public void setBatallaMasLarga(String texto) {
        lblEs2.setText("Batalla mas larga: " + texto);
    }

    public void setArmasHeroe(String texto) {
        lblEs3.setText("Total de armas invocadas heroe: " + texto);
    }

    public void setArmasVillano(String texto) {
        lblEs5.setText("Total de armas invocadas villano: " + texto);
    }

    public void setSupremosHeroe(String texto) {
        lblEs4.setText("Ataques supremos ejecutados heroe: " + texto);
    }

    public void setSupremosVillano(String texto) {
        lvlEs5.setText("Ataques supremos ejecutados villano: " + texto);
    }

    public void setWinrateHeroe(String texto) {
        lblEs6.setText("Winrate heroe %: " + texto);
    }

    public void setWinrateVillano(String texto) {
        lblEs7.setText("Winrate villano %: " + texto);
    }

    public javax.swing.JButton getBtnCerrar() {
        return btnVolver; // Mapeado a btnVolver ya que btnCerrar no existe en el form actual
    }

    // Métodos Header (no disponibles en el diseño actual, dejamos vacíos para
    // evitar error de compilación)
    public void setHeroeNombre(String texto) {
        /* No implementado en GUI actual */ }

    public void setVillanoNombre(String texto) {
        /* No implementado en GUI actual */ }

    public void setGanador(String texto) {
        /* No implementado en GUI actual */ }

    public void setTurnos(String texto) {
        /* No implementado en GUI actual */ }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEs1;
    private javax.swing.JLabel lblEs2;
    private javax.swing.JLabel lblEs3;
    private javax.swing.JLabel lblEs4;
    private javax.swing.JLabel lblEs5;
    private javax.swing.JLabel lblEs6;
    private javax.swing.JLabel lblEs7;
    private javax.swing.JLabel lvlEs5;
    private javax.swing.JTextArea txtCombatLog;
    // End of variables declaration//GEN-END:variables
}